// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txovwucfngggijkmwsox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4b3Z3dWNmbmdnZ2lqa213c294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTk0MjMsImV4cCI6MjA3MTUzNTQyM30.8hU4sGCNw0rHXk8haoAHsdbbC6KGlidy56acCc57sg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});